[2016-12-05 10:40:21] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /fonts/glyphicons-halflings-regular.woff2" (from "http://localhost/symfony_demo/web/css/bootstrap-flatly-3.3.7.min.css")" at C:\xampp\htdocs\symfony_demo\var\cache\prod\classes.php line 3877 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /fonts/glyphicons-halflings-regular.woff2\" (from \"http://localhost/symfony_demo/web/css/bootstrap-flatly-3.3.7.min.css\") at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\classes.php:3877, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:167)"} []
[2016-12-05 10:40:21] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /fonts/glyphicons-halflings-regular.woff" (from "http://localhost/symfony_demo/web/css/bootstrap-flatly-3.3.7.min.css")" at C:\xampp\htdocs\symfony_demo\var\cache\prod\classes.php line 3877 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /fonts/glyphicons-halflings-regular.woff\" (from \"http://localhost/symfony_demo/web/css/bootstrap-flatly-3.3.7.min.css\") at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\classes.php:3877, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:167)"} []
[2016-12-05 10:40:22] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /fonts/glyphicons-halflings-regular.ttf" (from "http://localhost/symfony_demo/web/css/bootstrap-flatly-3.3.7.min.css")" at C:\xampp\htdocs\symfony_demo\var\cache\prod\classes.php line 3877 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /fonts/glyphicons-halflings-regular.ttf\" (from \"http://localhost/symfony_demo/web/css/bootstrap-flatly-3.3.7.min.css\") at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\classes.php:3877, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:167)"} []
[2016-12-05 10:40:47] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /fonts/glyphicons-halflings-regular.woff2" (from "http://localhost/symfony_demo/web/css/bootstrap-flatly-3.3.7.min.css")" at C:\xampp\htdocs\symfony_demo\var\cache\prod\classes.php line 3877 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /fonts/glyphicons-halflings-regular.woff2\" (from \"http://localhost/symfony_demo/web/css/bootstrap-flatly-3.3.7.min.css\") at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\classes.php:3877, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:167)"} []
[2016-12-05 10:40:47] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /fonts/glyphicons-halflings-regular.woff" (from "http://localhost/symfony_demo/web/css/bootstrap-flatly-3.3.7.min.css")" at C:\xampp\htdocs\symfony_demo\var\cache\prod\classes.php line 3877 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /fonts/glyphicons-halflings-regular.woff\" (from \"http://localhost/symfony_demo/web/css/bootstrap-flatly-3.3.7.min.css\") at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\classes.php:3877, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:167)"} []
[2016-12-05 10:40:47] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /fonts/glyphicons-halflings-regular.ttf" (from "http://localhost/symfony_demo/web/css/bootstrap-flatly-3.3.7.min.css")" at C:\xampp\htdocs\symfony_demo\var\cache\prod\classes.php line 3877 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /fonts/glyphicons-halflings-regular.ttf\" (from \"http://localhost/symfony_demo/web/css/bootstrap-flatly-3.3.7.min.css\") at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\classes.php:3877, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:167)"} []
[2016-12-07 11:40:57] request.INFO: Matched route "blog_post". {"route":"blog_post","route_parameters":{"_controller":"AppBundle\\Controller\\BlogController::postShowAction","_locale":"ru","slug":"lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit","_route":"blog_post"},"request_uri":"http://localhost/symfony_demo/web/ru/blog/posts/lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit","method":"GET"} []
[2016-12-07 11:40:57] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-12-07 11:40:57] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The controller for URI "/ru/blog/posts/lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit" is not callable. Expected method "postShowAction" on class "AppBundle\Controller\BlogController". Available methods: "indexAction", "setContainer"." at C:\xampp\htdocs\symfony_demo\var\cache\prod\classes.php line 4097 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/ru/blog/posts/lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit\" is not callable. Expected method \"postShowAction\" on class \"AppBundle\\Controller\\BlogController\". Available methods: \"indexAction\", \"setContainer\". at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\classes.php:4097)"} []
[2016-12-07 12:14:54] request.INFO: Matched route "blog_index". {"route":"blog_index","route_parameters":{"page":"1","_controller":"AppBundle\\Controller\\BlogController::indexAction","_locale":"ru","_route":"blog_index"},"request_uri":"http://localhost/symfony_demo/web/ru/blog/","method":"GET"} []
[2016-12-07 12:14:54] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-12-07 12:14:54] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Unable to find template "blog/index.html.twig" (looked into: C:\xampp\htdocs\symfony_demo\app/Resources/views, C:\xampp\htdocs\symfony_demo\vendor\symfony\symfony\src\Symfony\Bridge\Twig/Resources/views/Form)." at C:\xampp\htdocs\symfony_demo\vendor\symfony\symfony\src\Symfony\Bridge\Twig\TwigEngine.php line 128 {"exception":"[object] (InvalidArgumentException(code: 0): Unable to find template \"blog/index.html.twig\" (looked into: C:\\xampp\\htdocs\\symfony_demo\\app/Resources/views, C:\\xampp\\htdocs\\symfony_demo\\vendor\\symfony\\symfony\\src\\Symfony\\Bridge\\Twig/Resources/views/Form). at C:\\xampp\\htdocs\\symfony_demo\\vendor\\symfony\\symfony\\src\\Symfony\\Bridge\\Twig\\TwigEngine.php:128, Twig_Error_Loader(code: 0): Unable to find template \"blog/index.html.twig\" (looked into: C:\\xampp\\htdocs\\symfony_demo\\app/Resources/views, C:\\xampp\\htdocs\\symfony_demo\\vendor\\symfony\\symfony\\src\\Symfony\\Bridge\\Twig/Resources/views/Form). at C:\\xampp\\htdocs\\symfony_demo\\vendor\\twig\\twig\\lib\\Twig\\Loader\\Filesystem.php:247)"} []
[2016-12-07 12:15:19] request.INFO: Matched route "blog_index". {"route":"blog_index","route_parameters":{"page":"1","_controller":"AppBundle\\Controller\\BlogController::indexAction","_locale":"ru","_route":"blog_index"},"request_uri":"http://localhost/symfony_demo/web/ru/blog/","method":"GET"} []
[2016-12-07 12:15:19] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-12-07 12:15:19] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Unable to find template "blog/index.html.twig" (looked into: C:\xampp\htdocs\symfony_demo\app/Resources/views, C:\xampp\htdocs\symfony_demo\vendor\symfony\symfony\src\Symfony\Bridge\Twig/Resources/views/Form)." at C:\xampp\htdocs\symfony_demo\vendor\symfony\symfony\src\Symfony\Bridge\Twig\TwigEngine.php line 128 {"exception":"[object] (InvalidArgumentException(code: 0): Unable to find template \"blog/index.html.twig\" (looked into: C:\\xampp\\htdocs\\symfony_demo\\app/Resources/views, C:\\xampp\\htdocs\\symfony_demo\\vendor\\symfony\\symfony\\src\\Symfony\\Bridge\\Twig/Resources/views/Form). at C:\\xampp\\htdocs\\symfony_demo\\vendor\\symfony\\symfony\\src\\Symfony\\Bridge\\Twig\\TwigEngine.php:128, Twig_Error_Loader(code: 0): Unable to find template \"blog/index.html.twig\" (looked into: C:\\xampp\\htdocs\\symfony_demo\\app/Resources/views, C:\\xampp\\htdocs\\symfony_demo\\vendor\\symfony\\symfony\\src\\Symfony\\Bridge\\Twig/Resources/views/Form). at C:\\xampp\\htdocs\\symfony_demo\\vendor\\twig\\twig\\lib\\Twig\\Loader\\Filesystem.php:247)"} []
[2016-12-07 15:01:32] request.INFO: Matched route "blog_post". {"route":"blog_post","route_parameters":{"_controller":"AppBundle\\Controller\\BlogController::postShowAction","_locale":"ru","slug":"pellentesque-et-sapien-pulvinar-consectetur","_route":"blog_post"},"request_uri":"http://localhost/symfony_demo/web/ru/blog/posts/pellentesque-et-sapien-pulvinar-consectetur","method":"GET"} []
[2016-12-07 15:01:32] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-12-07 15:01:32] security.DEBUG: User was reloaded from a user provider. {"username":"anna_admin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2016-12-07 15:01:34] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The controller for URI "/_fragment" is not callable. Expected method "commentFormAction" on class "AppBundle\Controller\BlogController". Available methods: "indexAction", "postShowAction", "setContainer"." at C:\xampp\htdocs\symfony_demo\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Controller\ControllerResolver.php line 90 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/_fragment\" is not callable. Expected method \"commentFormAction\" on class \"AppBundle\\Controller\\BlogController\". Available methods: \"indexAction\", \"postShowAction\", \"setContainer\". at C:\\xampp\\htdocs\\symfony_demo\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\Controller\\ControllerResolver.php:90)"} []
[2016-12-07 15:01:35] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-12-07 15:01:35] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-12-07 15:01:35] security.DEBUG: User was reloaded from a user provider. {"username":"anna_admin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2016-12-07 15:01:35] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-12-07 16:03:13] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"Symfony\\Bundle\\FrameworkBundle\\Controller\\TemplateController::templateAction","template":"default/homepage.html.twig","_locale":"ru","_route":"homepage"},"request_uri":"http://localhost/symfony_demo/web/ru","method":"GET"} []
[2016-12-07 16:03:15] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Maximum execution time of 30 seconds exceeded" at C:\xampp\htdocs\symfony_demo\vendor\symfony\symfony\src\Symfony\Component\Security\Csrf\TokenStorage\SessionTokenStorage.php line 22 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Maximum execution time of 30 seconds exceeded at C:\\xampp\\htdocs\\symfony_demo\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Csrf\\TokenStorage\\SessionTokenStorage.php:22)"} []
[2016-12-08 00:36:17] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /blog/"" at C:\xampp\htdocs\symfony_demo\var\cache\prod\classes.php line 3877 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /blog/\" at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\classes.php:3877, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:156)"} []
[2016-12-08 12:28:51] request.INFO: Matched route "blog_index". {"route":"blog_index","route_parameters":{"page":"1","_controller":"AppBundle\\Controller\\BlogController::indexAction","_locale":"en","_route":"blog_index"},"request_uri":"http://localhost/symfony_demo/web/en/blog/","method":"GET"} []
[2016-12-08 12:28:52] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-12-08 12:28:53] security.DEBUG: User was reloaded from a user provider. {"username":"anna_admin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2016-12-08 12:28:56] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Maximum execution time of 30 seconds exceeded" at C:\xampp\htdocs\symfony_demo\vendor\symfony\symfony\src\Symfony\Component\Routing\Generator\UrlGenerator.php line 28 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Maximum execution time of 30 seconds exceeded at C:\\xampp\\htdocs\\symfony_demo\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Routing\\Generator\\UrlGenerator.php:28)"} []
[2016-12-08 15:33:13] request.INFO: Matched route "blog_index". {"route":"blog_index","route_parameters":{"page":"1","_controller":"AppBundle\\Controller\\BlogController::indexAction","_locale":"en","_route":"blog_index"},"request_uri":"http://localhost/symfony_demo/web/en/blog/","method":"GET"} []
[2016-12-08 15:33:14] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-12-08 15:33:15] security.DEBUG: User was reloaded from a user provider. {"username":"anna_admin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2016-12-08 15:33:20] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Maximum execution time of 30 seconds exceeded" at C:\xampp\htdocs\symfony_demo\vendor\doctrine\orm\lib\Doctrine\ORM\Query\SqlWalker.php line 41 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Maximum execution time of 30 seconds exceeded at C:\\xampp\\htdocs\\symfony_demo\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\Query\\SqlWalker.php:41)"} []
[2016-12-08 15:33:21] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-12-12 13:26:37] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/myowncss1.css" (from "http://localhost/symfony_demo/web/ru/blog/")" at C:\xampp\htdocs\symfony_demo\var\cache\prod\classes.php line 3877 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /css/myowncss1.css\" (from \"http://localhost/symfony_demo/web/ru/blog/\") at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\classes.php:3877, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:156)"} []
[2016-12-12 14:10:43] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/myowncss1.css" (from "http://localhost/symfony_demo/web/ru/blog/")" at C:\xampp\htdocs\symfony_demo\var\cache\prod\classes.php line 3877 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /css/myowncss1.css\" (from \"http://localhost/symfony_demo/web/ru/blog/\") at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\classes.php:3877, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:156)"} []
[2016-12-12 14:12:03] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/"" at C:\xampp\htdocs\symfony_demo\var\cache\prod\classes.php line 3877 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/\" at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\classes.php:3877, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:156)"} []
[2016-12-12 14:20:09] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/myowncss1.css" (from "http://localhost/symfony_demo/web/ru/blog/")" at C:\xampp\htdocs\symfony_demo\var\cache\prod\classes.php line 3877 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /css/myowncss1.css\" (from \"http://localhost/symfony_demo/web/ru/blog/\") at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\classes.php:3877, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:156)"} []
[2016-12-12 14:36:01] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/bootstrap.css.map"" at C:\xampp\htdocs\symfony_demo\var\cache\prod\classes.php line 4595 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /css/bootstrap.css.map\" at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\classes.php:4595, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:156)"} []
[2016-12-12 14:38:38] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/bootstrap.css.map"" at C:\xampp\htdocs\symfony_demo\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /css/bootstrap.css.map\" at C:\\xampp\\htdocs\\symfony_demo\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:156)"} []
[2016-12-12 14:38:48] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/bootstrap.css.map"" at C:\xampp\htdocs\symfony_demo\var\cache\prod\classes.php line 4595 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /css/bootstrap.css.map\" at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\classes.php:4595, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:156)"} []
[2016-12-12 21:22:22] request.INFO: Matched route "blog_post". {"route":"blog_post","route_parameters":{"_controller":"AppBundle\\Controller\\BlogController::postShowAction","_locale":"ru","slug":"фыв-апр","_route":"blog_post"},"request_uri":"http://localhost/symfony_demo/web/ru/blog/posts/%D1%84%D1%8B%D0%B2-%D0%B0%D0%BF%D1%80","method":"GET"} []
[2016-12-12 21:22:22] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-12-12 21:22:22] security.DEBUG: User was reloaded from a user provider. {"username":"anna_admin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2016-12-12 21:22:22] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The controller for URI "/_fragment" is not callable. Expected method "commentFormAction" on class "AppBundle\Controller\BlogController". Available methods: "indexAction", "postShowAction", "setContainer"." at C:\xampp\htdocs\symfony_demo\var\cache\prod\classes.php line 4815 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/_fragment\" is not callable. Expected method \"commentFormAction\" on class \"AppBundle\\Controller\\BlogController\". Available methods: \"indexAction\", \"postShowAction\", \"setContainer\". at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\classes.php:4815)"} []
[2016-12-12 21:22:22] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-12-12 21:22:51] request.INFO: Matched route "blog_post". {"route":"blog_post","route_parameters":{"_controller":"AppBundle\\Controller\\BlogController::postShowAction","_locale":"ru","slug":"фыв-апр","_route":"blog_post"},"request_uri":"http://localhost/symfony_demo/web/ru/blog/posts/%D1%84%D1%8B%D0%B2-%D0%B0%D0%BF%D1%80","method":"GET"} []
[2016-12-12 21:22:51] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-12-12 21:22:51] security.DEBUG: User was reloaded from a user provider. {"username":"anna_admin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2016-12-12 21:22:51] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The controller for URI "/_fragment" is not callable. Expected method "commentFormAction" on class "AppBundle\Controller\BlogController". Available methods: "indexAction", "postShowAction", "setContainer"." at C:\xampp\htdocs\symfony_demo\var\cache\prod\classes.php line 4097 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/_fragment\" is not callable. Expected method \"commentFormAction\" on class \"AppBundle\\Controller\\BlogController\". Available methods: \"indexAction\", \"postShowAction\", \"setContainer\". at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\classes.php:4097)"} []
[2016-12-12 21:22:51] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-12-12 21:22:58] request.INFO: Matched route "blog_post". {"route":"blog_post","route_parameters":{"_controller":"AppBundle\\Controller\\BlogController::postShowAction","_locale":"ru","slug":"lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit","_route":"blog_post"},"request_uri":"http://localhost/symfony_demo/web/ru/blog/posts/lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit","method":"GET"} []
[2016-12-12 21:22:58] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-12-12 21:22:58] security.DEBUG: User was reloaded from a user provider. {"username":"anna_admin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2016-12-12 21:22:58] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The controller for URI "/_fragment" is not callable. Expected method "commentFormAction" on class "AppBundle\Controller\BlogController". Available methods: "indexAction", "postShowAction", "setContainer"." at C:\xampp\htdocs\symfony_demo\var\cache\prod\classes.php line 4097 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/_fragment\" is not callable. Expected method \"commentFormAction\" on class \"AppBundle\\Controller\\BlogController\". Available methods: \"indexAction\", \"postShowAction\", \"setContainer\". at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\classes.php:4097)"} []
[2016-12-12 21:22:58] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-12-12 21:29:30] request.INFO: Matched route "blog_post". {"route":"blog_post","route_parameters":{"_controller":"AppBundle\\Controller\\BlogController::postShowAction","_locale":"ru","slug":"eros-diam-egestas-libero-eu-vulputate-risus","_route":"blog_post"},"request_uri":"http://localhost/symfony_demo/web/ru/blog/posts/eros-diam-egestas-libero-eu-vulputate-risus","method":"GET"} []
[2016-12-12 21:29:30] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-12-12 21:29:30] security.DEBUG: User was reloaded from a user provider. {"username":"anna_admin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2016-12-12 21:29:31] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The controller for URI "/_fragment" is not callable. Expected method "commentFormAction" on class "AppBundle\Controller\BlogController". Available methods: "indexAction", "postShowAction", "setContainer"." at C:\xampp\htdocs\symfony_demo\var\cache\prod\classes.php line 4815 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/_fragment\" is not callable. Expected method \"commentFormAction\" on class \"AppBundle\\Controller\\BlogController\". Available methods: \"indexAction\", \"postShowAction\", \"setContainer\". at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\classes.php:4815)"} []
[2016-12-12 21:29:31] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-12-12 22:02:43] request.INFO: Matched route "blog_post". {"route":"blog_post","route_parameters":{"_controller":"AppBundle\\Controller\\BlogController::postShowAction","_locale":"ru","slug":"lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit","_route":"blog_post"},"request_uri":"http://localhost/symfony_demo/web/ru/blog/posts/lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit","method":"GET"} []
[2016-12-12 22:02:43] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-12-12 22:02:43] security.DEBUG: User was reloaded from a user provider. {"username":"anna_admin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2016-12-12 22:02:43] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The controller for URI "/_fragment" is not callable. Expected method "commentFormAction" on class "AppBundle\Controller\BlogController". Available methods: "indexAction", "postShowAction", "setContainer"." at C:\xampp\htdocs\symfony_demo\var\cache\prod\classes.php line 4815 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/_fragment\" is not callable. Expected method \"commentFormAction\" on class \"AppBundle\\Controller\\BlogController\". Available methods: \"indexAction\", \"postShowAction\", \"setContainer\". at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\classes.php:4815)"} []
[2016-12-12 22:02:43] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-12-12 22:04:34] request.INFO: Matched route "blog_post". {"route":"blog_post","route_parameters":{"_controller":"AppBundle\\Controller\\BlogController::postShowAction","_locale":"ru","slug":"lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit","_route":"blog_post"},"request_uri":"http://localhost/symfony_demo/web/ru/blog/posts/lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit","method":"GET"} []
[2016-12-12 22:04:34] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-12-12 22:04:35] security.DEBUG: User was reloaded from a user provider. {"username":"anna_admin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2016-12-12 22:04:35] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The controller for URI "/_fragment" is not callable. Expected method "commentFormAction" on class "AppBundle\Controller\BlogController". Available methods: "indexAction", "postShowAction", "setContainer"." at C:\xampp\htdocs\symfony_demo\var\cache\prod\classes.php line 4097 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/_fragment\" is not callable. Expected method \"commentFormAction\" on class \"AppBundle\\Controller\\BlogController\". Available methods: \"indexAction\", \"postShowAction\", \"setContainer\". at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\classes.php:4097)"} []
[2016-12-12 22:04:35] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-12-12 23:08:47] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/blog/" (from "http://localhost/symfony_demo/web/ru/admin/post/")" at C:\xampp\htdocs\symfony_demo\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/blog/\" (from \"http://localhost/symfony_demo/web/ru/admin/post/\") at C:\\xampp\\htdocs\\symfony_demo\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\symfony_demo\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:156)"} []
[2016-12-12 23:11:21] request.INFO: Matched route "admin_index". {"route":"admin_index","route_parameters":{"_controller":"AppBundle\\Controller\\Admin\\BlogController::indexAction","_locale":"ru","_route":"admin_index"},"request_uri":"http://localhost/symfony_demo/web/ru/admin/post/","method":"GET"} []
[2016-12-12 23:11:21] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-12-12 23:11:21] security.DEBUG: User was reloaded from a user provider. {"username":"john_user","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2016-12-12 23:11:21] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\symfony_demo\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:70)"} []
[2016-12-12 23:11:21] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at C:\xampp\htdocs\symfony_demo\vendor\symfony\symfony\src\Symfony\Component\Security\Http\Firewall\ExceptionListener.php line 122 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at C:\\xampp\\htdocs\\symfony_demo\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\ExceptionListener.php:122, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\symfony_demo\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:70)"} []
[2016-12-12 23:11:21] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-12-12 23:11:41] request.INFO: Matched route "admin_index". {"route":"admin_index","route_parameters":{"_controller":"AppBundle\\Controller\\Admin\\BlogController::indexAction","_locale":"ru","_route":"admin_index"},"request_uri":"http://localhost/symfony_demo/web/ru/admin/post/","method":"GET"} []
[2016-12-12 23:11:41] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-12-12 23:11:41] security.DEBUG: User was reloaded from a user provider. {"username":"john_user","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2016-12-12 23:11:41] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\symfony_demo\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:70)"} []
[2016-12-12 23:11:41] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at C:\xampp\htdocs\symfony_demo\vendor\symfony\symfony\src\Symfony\Component\Security\Http\Firewall\ExceptionListener.php line 122 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at C:\\xampp\\htdocs\\symfony_demo\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\ExceptionListener.php:122, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\symfony_demo\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:70)"} []
[2016-12-12 23:11:41] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
